# Generated by Django 2.0.3 on 2018-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match_team_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_ID', models.IntegerField()),
                ('Round', models.IntegerField()),
                ('Home_team_name', models.CharField(max_length=50)),
                ('Away_team_name', models.CharField(max_length=50)),
                ('Home_team_score', models.IntegerField()),
                ('Away_team_score', models.IntegerField()),
            ],
        ),
    ]
