# Generated by Django 2.0.3 on 2018-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match_ID', models.IntegerField()),
                ('Home_team_name', models.CharField(max_length=50)),
                ('Away_team_name', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
    ]
