# Generated by Django 2.0.3 on 2018-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_auto_20180415_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='FullName',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
