# Generated by Django 2.0.3 on 2018-05-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_gamepenaltieslog_gameplayerlog_gameteamlog_generalplayer_generalschedule_generalteam_playerfitnesslo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayerlog',
            old_name='EvenDefence',
            new_name='EventDefence',
        ),
    ]
