# Generated by Django 2.0.3 on 2018-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0006_auto_20180530_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalplayer',
            name='PlayerImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
