# Generated by Django 2.0.3 on 2018-05-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0010_auto_20180531_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalplayer',
            name='AdjustedName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
