# Generated by Django 2.0.3 on 2018-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0011_generalplayer_adjustedname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplayer',
            name='DivisionRank',
            field=models.IntegerField(blank=True),
        ),
    ]
