# Generated by Django 2.0.3 on 2018-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0012_auto_20180531_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplayer',
            name='DivisionRank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
