# Generated by Django 2.0.3 on 2018-06-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0013_auto_20180531_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalschedule',
            old_name='Round',
            new_name='TournamnetRound',
        ),
    ]
