# Generated by Django 2.0.3 on 2018-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0014_auto_20180602_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalschedule',
            name='Played',
            field=models.BooleanField(default=False),
        ),
    ]
