# Generated by Django 2.0.3 on 2018-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0015_auto_20180602_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalschedule',
            name='AfterPenaltyAway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='AfterPenaltyHome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='DivisionAway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='DivisionHome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='FocusedEvent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigeCupAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigeCupHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsFocusedEvent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
