# Generated by Django 2.0.3 on 2018-06-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0017_auto_20180602_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermotivationlog',
            name='Day',
        ),
    ]
