# Generated by Django 2.0.3 on 2018-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0019_playermotivationlog_motivationchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteamlog',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='AttackingTeam',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='Away',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='AwayGoalsAfterAttack',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='DivisionPlaceBeforeGameAway',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='DivisionPlaceBeforeGameHome',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='EventPlayer',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='FavoriteStatusAway',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='FavoriteStatusHome',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='HomeGoalsAfterAttack',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='PrestigeAway',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='PrestigeHome',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='TeamMotivation',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='TeamMotivationChange',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='Tournament',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='TournamentRound',
        ),
        migrations.RemoveField(
            model_name='gameteamlog',
            name='TransactionID',
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='AttckingArea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='DefenceResult',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='DefendingArea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='GoalsAgainstAfterRound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='GoalsForwardAfterRound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='HomeOrAway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='Motivation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='MotivationChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='TacticsValueChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameteamlog',
            name='TeamName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameteamlog',
            name='AttackResult',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameteamlog',
            name='GameNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameteamlog',
            name='GameRound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameteamlog',
            name='Tactics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameteamlog',
            name='TacticsValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermotivationlog',
            name='MotivationChange',
            field=models.FloatField(default=0),
        ),
    ]
