# Generated by Django 2.0.3 on 2018-06-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0021_auto_20180607_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteamlog',
            name='MotivationChange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
