# Generated by Django 2.0.3 on 2018-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0023_auto_20180609_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='ChangeDefensiveEvent',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='ChangeDefensivePerformance',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='ChangeOffensiveEvent',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='ChangeOffensivePerformance',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='EventAttack',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='EventDefence',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='GoalAway',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='GoalHome',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='LoyaltyPoints',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='NewDefensiveAbility',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='NewOffensiveAbility',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='Performance',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='RoutinePoints',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='TeamPlayerID',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='TotalChangeAbility',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='TotalChangeDefensive',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='TotalChangeOffensive',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='Tournament',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='TournanementRound',
        ),
        migrations.RemoveField(
            model_name='gameplayerlog',
            name='TransactionID',
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='Ability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='AdjustedPersonalMotivation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='AttackAbility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefendAbility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefensiveAbility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefensiveAbilityChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefensiveRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefensiveValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='GoalOffAbilityChange',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='MotivationAdjustedDefensivePerformance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='MotivationAdjustedOffensivePerformance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='OffensiveAbility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='OffensiveAbilityChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='OffensiveRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='OffensiveValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='PersonalMotivationChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='SaveDefAbilityChange',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='TotalMotivationChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='AreaAttack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='AreaDefence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='Chemestry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='DefensivePerformance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='FitnessChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='GameNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='GameRound',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='MotivationChange',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='NewFitness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='NewMotivation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='OffensivePerformance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='PlayerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='Position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='Team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
