# Generated by Django 2.0.3 on 2018-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0024_auto_20180611_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='PersonalMotivation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
