# Generated by Django 2.0.3 on 2018-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0025_gameplayerlog_personalmotivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayerlog',
            old_name='GameNumber',
            new_name='GameID',
        ),
        migrations.RenameField(
            model_name='gameteamlog',
            old_name='GameNumber',
            new_name='GameID',
        ),
        migrations.AddField(
            model_name='playermotivationlog',
            name='Day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermotivationlog',
            name='GameID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playermotivationlog',
            name='TypeOfUpdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='Day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='DivisionPlaceAway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='DivisionPlaceDifference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='DivisionPlaceHome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='GameID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='GameNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='GoalsAway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='GoalsHome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsBasic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsDivisionBasic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsRivalryAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsRivalryHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsTotalAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='PrestigePointsTotalHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='RoutinePoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationFavouriteStatusAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationFavouriteStatusHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationPreviousRoundAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationPreviousRoundHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationSituationAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamMotivationSituationHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRankAway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRankDifference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRankDivisionAway',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRankDivisionDifference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRankDivisionHome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRankHome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRivalryAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRivalryHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamRivalryTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamTacticsAway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamTacticsGameValueAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamTacticsGameValueHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamTacticsHome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamTacticsValueAway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TeamTacticsValueHome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='Tournament',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='TypeOfGame',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='Week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalschedule',
            name='Winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playermotivationlog',
            name='Motivation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playermotivationlog',
            name='MotivationChange',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playermotivationlog',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
