# Generated by Django 2.0.3 on 2018-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0026_auto_20180612_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerfitnesslog',
            name='LastMatchDay',
        ),
        migrations.RemoveField(
            model_name='playerfitnesslog',
            name='NewFitness',
        ),
        migrations.RemoveField(
            model_name='playerfitnesslog',
            name='PreviousFitness',
        ),
        migrations.RemoveField(
            model_name='playerfitnesslog',
            name='RecoveredFitness',
        ),
        migrations.RemoveField(
            model_name='playerfitnesslog',
            name='TransactionID',
        ),
        migrations.RemoveField(
            model_name='playerfitnesslog',
            name='Week',
        ),
        migrations.AddField(
            model_name='playerfitnesslog',
            name='Fitness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerfitnesslog',
            name='FitnessChange',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerfitnesslog',
            name='GameID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerfitnesslog',
            name='TypeOfUpdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerfitnesslog',
            name='Day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerfitnesslog',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
