# Generated by Django 2.0.3 on 2018-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0027_auto_20180613_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAbilityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OffensiveAbilityChange', models.FloatField(blank=True, default=0, null=True)),
                ('OffensiveAbility', models.FloatField(blank=True, null=True)),
                ('DefensiveAbilityChange', models.FloatField(blank=True, default=0, null=True)),
                ('DefensiveAbility', models.FloatField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('TypeOfUpdate', models.CharField(blank=True, max_length=100, null=True)),
                ('GameID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
