# Generated by Django 2.0.3 on 2018-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0028_playerabilitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMotivationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MotivationChange', models.FloatField(blank=True, null=True)),
                ('Motivation', models.FloatField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('TypeOfUpdate', models.CharField(blank=True, max_length=100, null=True)),
                ('GameID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
