# Generated by Django 2.0.3 on 2018-06-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0029_teammotivationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalplayer',
            name='AdjustedName',
        ),
    ]
