# Generated by Django 2.0.3 on 2018-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0031_remove_generalplayer_adjustmentfactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPlayerCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ability', models.FloatField()),
                ('DefensiveAbility', models.FloatField()),
                ('DivisionRank', models.IntegerField(blank=True, null=True)),
                ('Fitness', models.FloatField()),
                ('GKPosExperience', models.FloatField()),
                ('LMPosExperience', models.FloatField()),
                ('Nation', models.CharField(max_length=100)),
                ('OffensiveAbility', models.FloatField()),
                ('PlayerChemistry', models.FloatField()),
                ('PlayerMotivation', models.FloatField()),
                ('Name', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('RMPosExperience', models.FloatField()),
                ('Routine', models.IntegerField()),
                ('RoutineRank', models.FloatField()),
                ('STPosExperience', models.FloatField()),
                ('Team', models.CharField(max_length=100)),
                ('TeamPlayerID', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
