# Generated by Django 2.0.3 on 2018-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0032_generalplayercopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalplayercopy',
            name='test',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
