# Generated by Django 2.0.3 on 2018-06-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0033_generalplayercopy_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalplayercopy',
            name='test',
        ),
    ]
