# Generated by Django 2.0.3 on 2018-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0034_remove_generalplayercopy_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('Week', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
