# Generated by Django 2.0.3 on 2018-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0035_daytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalschedule',
            name='QualificationAway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalschedule',
            name='QualificationHome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalschedule',
            name='SchedulingIdentifyerAway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalschedule',
            name='SchedulingIdentifyerHome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalteam',
            name='SeedingNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalteam',
            name='NoOfPlayers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
