# Generated by Django 2.0.3 on 2018-10-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0038_auto_20181007_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerfitnesslog',
            old_name='NewFitness',
            new_name='NFitness',
        ),
    ]
