# Generated by Django 2.0.3 on 2018-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0040_auto_20181007_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFitnessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OldFitness', models.FloatField(blank=True, default=0, null=True)),
                ('FitnessChange', models.FloatField(blank=True, default=0, null=True)),
                ('NewFitness', models.FloatField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Team', models.CharField(blank=True, max_length=100, null=True)),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('TypeOfUpdate', models.CharField(blank=True, max_length=100, null=True)),
                ('GameID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
