# Generated by Django 2.0.3 on 2018-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0041_tempfitnesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMotivationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OldMotivation', models.FloatField(blank=True, default=0, null=True)),
                ('MotivationChange', models.FloatField(blank=True, default=0, null=True)),
                ('NewMotivation', models.FloatField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Team', models.CharField(blank=True, max_length=100, null=True)),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('TypeOfUpdate', models.CharField(blank=True, max_length=100, null=True)),
                ('GameID', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='playermotivationlog',
            old_name='Motivation',
            new_name='NewMotivation',
        ),
        migrations.AddField(
            model_name='playermotivationlog',
            name='OldMotivation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playermotivationlog',
            name='Team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
