# Generated by Django 2.0.3 on 2018-10-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0042_auto_20181007_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayerlog',
            old_name='PlayerName',
            new_name='Name',
        ),
    ]
