# Generated by Django 2.0.3 on 2018-10-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0043_auto_20181014_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerlog',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.GeneralPlayer'),
        ),
    ]
