# Generated by Django 2.0.3 on 2018-10-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0044_auto_20181014_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerlog',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
