# Generated by Django 2.0.3 on 2018-10-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0045_auto_20181014_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Team',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
