# Generated by Django 2.0.3 on 2018-10-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0046_auto_20181014_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralPlayerCopy',
        ),
    ]
