# Generated by Django 2.0.3 on 2018-10-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0047_delete_generalplayercopy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fixture',
        ),
        migrations.DeleteModel(
            name='Match_team_data',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
