# Generated by Django 2.0.3 on 2018-10-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0048_auto_20181014_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralPlayer',
            new_name='Player',
        ),
    ]
