# Generated by Django 2.0.3 on 2018-10-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0049_auto_20181014_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='Player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Player'),
        ),
    ]
