# Generated by Django 2.0.3 on 2018-10-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0055_tempmotivationlog_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermotivationlog',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='playermotivationlog',
            name='Team',
        ),
        migrations.AddField(
            model_name='playermotivationlog',
            name='Player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Player'),
        ),
    ]
