# Generated by Django 2.0.3 on 2018-10-21 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0056_auto_20181019_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteamlog',
            name='EventPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Player'),
        ),
    ]
