# Generated by Django 2.0.3 on 2018-12-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0058_auto_20181021_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='Substitute',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
