# Generated by Django 2.0.3 on 2018-12-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0059_gameplayerlog_substitute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralTeam',
            new_name='Team',
        ),
    ]
