# Generated by Django 2.0.3 on 2018-12-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0060_auto_20181209_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalschedule',
            name='AwayTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwayTeam', to='season.Team'),
        ),
        migrations.AddField(
            model_name='generalschedule',
            name='HomeTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeTeam', to='season.Team'),
        ),
    ]
