# Generated by Django 2.0.3 on 2018-12-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0061_auto_20181209_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=10)),
                ('calendar_class', models.CharField(max_length=100)),
                ('calendar_datatoggle', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
            ],
        ),
    ]
