# Generated by Django 2.0.3 on 2018-12-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0062_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='calendar_datatarget',
            field=models.CharField(default='.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='calendar_expanded',
            field=models.CharField(default='false', max_length=100),
            preserve_default=False,
        ),
    ]
