# Generated by Django 2.0.3 on 2018-12-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0063_auto_20181218_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='calendar_datatoggle',
        ),
    ]
