# Generated by Django 2.0.3 on 2018-12-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0065_tournament_calendar_div_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalschedule',
            old_name='Tournament',
            new_name='TournamentName',
        ),
    ]
