# Generated by Django 2.0.3 on 2018-12-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0066_auto_20181223_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalschedule',
            name='Tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Tournament'),
        ),
    ]
