# Generated by Django 2.0.3 on 2018-12-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0067_generalschedule_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminfo',
            old_name='Stadium',
            new_name='ArenaDescription',
        ),
    ]
