# Generated by Django 2.0.3 on 2019-01-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0068_auto_20181228_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdivisiondata',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Team'),
        ),
    ]
