# Generated by Django 2.0.3 on 2019-01-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0069_teamdivisiondata_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdivisiondata',
            name='Team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Team'),
        ),
    ]
