# Generated by Django 2.0.3 on 2019-01-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0070_auto_20190127_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdivisiondata',
            name='Tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Tournament'),
        ),
        migrations.AlterField(
            model_name='teamdivisiondata',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Team'),
        ),
    ]
