# Generated by Django 2.0.3 on 2019-02-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0072_auto_20190207_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='TeamPlayerID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
