# Generated by Django 2.0.3 on 2019-02-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0073_auto_20190207_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Flag', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
