# Generated by Django 2.0.3 on 2019-02-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0074_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Nation'),
        ),
    ]
