# Generated by Django 2.0.3 on 2019-02-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0075_auto_20190207_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerlog',
            name='GoalPlayer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameplayerlog',
            name='SavePlayer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
