# Generated by Django 2.0.3 on 2019-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0076_auto_20190209_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='MatchRating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
