# Generated by Django 2.0.3 on 2019-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0079_auto_20190223_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='AttackIntensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefenceIntensity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
