# Generated by Django 2.0.3 on 2019-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0080_auto_20190223_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='RoutineBonus',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
