# Generated by Django 2.0.3 on 2019-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0081_gameplayerlog_routinebonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='Nervosity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
