# Generated by Django 2.0.3 on 2019-02-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0082_gameplayerlog_nervosity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='TeamMotivation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='TeamMotivationChange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
