# Generated by Django 2.0.3 on 2019-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0084_auto_20190223_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerlog',
            name='AttackAreaInfluence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayerlog',
            name='DefenceAreaInfluence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
