# Generated by Django 2.0.3 on 2019-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0085_auto_20190223_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerlog',
            name='GoalOffAbilityChange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
