# Generated by Django 2.0.3 on 2019-02-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0087_auto_20190224_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayerlog',
            name='SaveDefAbilityChange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
