# Generated by Django 2.2.1 on 2019-05-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0089_auto_20190323_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Team'),
        ),
    ]
