# Generated by Django 2.2.1 on 2019-05-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0090_teaminfo_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalschedule',
            name='AwayTeam',
        ),
        migrations.RemoveField(
            model_name='generalschedule',
            name='HomeTeam',
        ),
    ]
