# Generated by Django 2.2.1 on 2019-05-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0092_auto_20190525_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalschedule',
            name='AwayTeam',
        ),
        migrations.RemoveField(
            model_name='generalschedule',
            name='HomeTeam',
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.Team'),
        ),
    ]
