# Generated by Django 2.2.1 on 2019-05-24 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0093_auto_20190525_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='season.Team'),
        ),
    ]
