# Generated by Django 2.2.1 on 2019-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0096_auto_20190525_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='Arena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
