# Generated by Django 2.2.1 on 2019-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0097_auto_20190525_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='ArenaDescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='Background',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='FanClub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='FanClubDescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='FullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
