# Generated by Django 2.2.1 on 2019-05-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0098_auto_20190525_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='Name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='Team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='season.Team'),
        ),
    ]
