# Generated by Django 2.2.1 on 2019-05-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0100_auto_20190526_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalschedule',
            name='AwayTeam',
        ),
        migrations.RemoveField(
            model_name='generalschedule',
            name='HomeTeam',
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='Team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='season.Team'),
        ),
    ]
