# Generated by Django 2.2.1 on 2019-05-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0102_auto_20190527_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='FanClub',
        ),
        migrations.RemoveField(
            model_name='team',
            name='FanClubDescription',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Stadium',
        ),
        migrations.RemoveField(
            model_name='team',
            name='StadiumDescription',
        ),
    ]
