# Generated by Django 2.2.5 on 2019-09-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0103_auto_20190529_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='ArenaDescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
